### ISSUE TITLE
[Feature] Lobby - start

### ISSUE THREAD

**Issue by gjsk132** [gjsk132/Lootify#2]
### 작업할 기능💡

플레이어가 게임을 시작하기 전 방을 생성할지, 방에 입장할지 등을 선택할 수 있는 공간
![start](https://github.com/user-attachments/assets/3f2e0263-4284-482b-8d9b-7d24a2e2b517)

### Todo

필요한 CustomView
---
- [x] SmallButton
- [x] Dialog-base

Feature
---
- [x] 화면 디자인
- [ ] Create Map 화면 이동
- [ ] My Map 화면 이동
- [ ] Create Room 화면 이동
- [ ] History 화면 이동
- [ ] Enter 구현

### 기타사항

다음 엑티비티 구현 후에 하나씩 진행하기
