### ISSUE TITLE
[Feature] Create Map - start

### ISSUE THREAD

**Issue by gjsk132** [gjsk132/Lootify#4]
### 작업할 기능💡

방을 생성하기 앞서, 보물지도(맵)을 설정하는 공간
![Map Creator start](https://github.com/user-attachments/assets/10e5d807-629b-4b5f-9356-47ab1effcf80)

### Todo

**Step1**
- [x] 화면 디자인
- [x] 각 버튼에 맞춰 Dialog 띄우기

**Step2**
- [ ] Dialog에 설정한 값의 수를 우측에 띄우고, 내 local DB에 저장하기

**Step3**
- [ ] Preview로 설정한 위치 볼 수 있게 하기
- [ ] local DB에 저장

### 기타사항

Lobby랑 비슷하게 다른 Issue에서 구현한 후에 연결하기~
