### ISSUE TITLE
[Feature] Create Map - Setting Dialog

### ISSUE THREAD

**Issue by gjsk132** [gjsk132/Lootify#7]
### 작업할 기능💡

보물을 세팅하는 공간
![Map Creator treasure](https://github.com/user-attachments/assets/dfd61a17-466c-4e7f-bd46-d04cd96a6f97)

### Todo

- [ ] 리사이클러뷰로 List 구현
- [ ] List 갯수 카운트해서 띄우기

## 세팅화면 구현하기
- [ ] 이름 설정화면
- [ ] AR icon 선택화면
- [ ] 최종 확인 화면
